export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';


export const AGREGAR_LIBRO = 'AGREGAR_LIBRO';
export const AGREGAR_LIBRO_EXITO = 'AGREGAR_LIBRO_EXITO';
export const AGREGAR_LIBRO_ERROR = 'AGREGAR_LIBRO_ERROR';


export const DESCARGAR_LIBRO = 'DESCARGAR_LIBRO';
export const DESCARGAR_LIBRO_EXITO = 'DESCARGAR_LIBRO_EXITO';
export const DESCARGAR_LIBRO_ERROR = 'DESCARGAR_LIBRO_ERROR';

export const ELIMINAR_LIBRO_ERROR = 'ELIMINAR_LIBRO_ERROR';
export const ELIMINAR_LIBRO = 'ELIMINAR_LIBRO';
export const ELIMINAR_LIBRO_EXITO = 'ELIMINAR_LIBRO_EXITO';

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const OBTENER_PRODUCTO_EDITAR_EXITO = 'OBTENER_PRODUCTO_EDITAR_EXITO';
export const OBTENER_PRODUCTO_EDITAR_ERROR = 'OBTENER_PRODUCTO_EDITAR_ERROR';

export const EDITAR_LIBRO = 'EDITAR_LIBRO';
export const EDITAR_LIBRO_EXITO = 'EDITAR_LIBRO_EXITO';
export const EDITAR_LIBRO_ERROR = 'EDITAR_LIBRO_ERROR';